name = "GmshReader"
uuid = "20219dce-5ca2-40bc-979b-617c665cec18"
authors = ["Thomas Cheng thomasc791@gmail.com"]
version = "0.1.3"

[compat]
Test = "1.11.0"
julia = "1.11.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
